name: Unit Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-26
    steps:
      - uses: actions/checkout@v7
      - uses: tanaabased/actions/setup-bun@v1
      - run: bun install --frozen-lockfile --ignore-scripts
      - run: bun run test
